feature: operator-management
title: オペレーター管理要件定義

introduction: |
  システム管理者（gyam様）がオペレーター（不動産会社）を管理する機能。
  オペレーターの登録、契約管理、サブスクリプション管理、システム全体の統計表示を行う。

requirements:
  - id: 1
    title: オペレーター登録
    objective: As an admin, I want to register new operators, so that real estate companies can use the system
    acceptance_criteria:
      - id: 1.1
        description: 管理者は新規オペレーターを登録できる
      - id: 1.2
        description: 登録時に企業情報（会社名、住所、電話、メール）を入力する
      - id: 1.3
        description: 登録時にサブスクリプションプラン（basic, standard, premium）を選択する
      - id: 1.4
        description: システムはオペレーター用のユーザーアカウントを作成する

  - id: 2
    title: オペレーター一覧・検索
    objective: As an admin, I want to view and search operators, so that I can manage them efficiently
    acceptance_criteria:
      - id: 2.1
        description: 管理者は全オペレーターの一覧を表示できる
      - id: 2.2
        description: システムはサブスクリプション状態（active, suspended, cancelled, trial）でフィルタリングできる
      - id: 2.3
        description: システムは会社名で検索できる
      - id: 2.4
        description: 一覧には物件数、顧客数などの統計を表示する

  - id: 3
    title: オペレーター詳細・編集
    objective: As an admin, I want to edit operator details, so that I can keep information up to date
    acceptance_criteria:
      - id: 3.1
        description: 管理者はオペレーターの詳細情報を確認できる
      - id: 3.2
        description: 管理者は企業情報を編集できる
      - id: 3.3
        description: 管理者はサブスクリプション状態を変更できる
      - id: 3.4
        description: 管理者はオペレーターを無効化（is_active=false）できる

  - id: 4
    title: オペレーター削除
    objective: As an admin, I want to delete operators, so that I can remove inactive companies
    acceptance_criteria:
      - id: 4.1
        description: 管理者はオペレーターを削除できる
      - id: 4.2
        description: 削除時に確認ダイアログを表示する
      - id: 4.3
        description: 削除時に関連データ（物件、顧客、会話）もCASCADE削除される

  - id: 5
    title: システム統計ダッシュボード
    objective: As an admin, I want to see system statistics, so that I can monitor overall usage
    acceptance_criteria:
      - id: 5.1
        description: システムは全オペレーター数（状態別）を表示する
      - id: 5.2
        description: システムは全物件数を表示する
      - id: 5.3
        description: システムは全顧客数を表示する
      - id: 5.4
        description: システムは直近30日の会話数を表示する
      - id: 5.5
        description: システムはオペレーター別の統計を表示する

roles:
  - name: admin
    description: システム管理者（gyam様）
