feature: chrome-extension
title: Chrome拡張機能（物件取り込み）要件定義

introduction: |
  アットホーム等の不動産ポータルサイトから物件情報をワンクリックで取り込むChrome拡張機能。
  GPT-4oで構造化データを抽出し、法的証跡としてHTMLスナップショットも保存する。

requirements:
  - id: 1
    title: 物件ページ検出
    objective: As an operator, I want the extension to detect property pages, so that I can import listings easily
    acceptance_criteria:
      - id: 1.1
        description: アットホームの物件詳細ページを開くと、拡張機能アイコンがアクティブになる
      - id: 1.2
        description: システムは対応サイト（アットホーム、SUUMO等）を検出する
      - id: 1.3
        description: 非対応サイトの場合、拡張機能アイコンがグレーアウトする

  - id: 2
    title: ワンクリック取り込み
    objective: As an operator, I want to import properties with one click, so that I can save time
    acceptance_criteria:
      - id: 2.1
        description: 拡張機能アイコンをクリックすると、ポップアップが表示される
      - id: 2.2
        description: 「取り込み」ボタンをクリックすると、システムはページHTMLを取得する
      - id: 2.3
        description: システムはAPIにHTML+URLを送信する
      - id: 2.4
        description: 取り込み完了後、システムは成功通知を表示する

  - id: 3
    title: 構造化データ抽出
    objective: As a system, I want to extract structured data from HTML, so that properties can be searchable
    acceptance_criteria:
      - id: 3.1
        description: システムはGPT-4oでHTMLから物件情報を抽出する
      - id: 3.2
        description: "抽出情報: タイトル、住所、エリア、賃料、間取り、建物種別、駅、駅徒歩、設備等"
      - id: 3.3
        description: システムはOpenAI Embeddingsでベクトル埋め込みを生成する

  - id: 4
    title: HTMLスナップショット保存
    objective: As a system, I want to save HTML snapshots, so that I have legal evidence of the import source
    acceptance_criteria:
      - id: 4.1
        description: システムは取り込み元HTMLをSupabase Storageに保存する
      - id: 4.2
        description: システムは取り込みログ（URL、日時、担当者）をDBに記録する
      - id: 4.3
        description: オペレーターは取り込み履歴を確認できる

  - id: 5
    title: 認証連携
    objective: As an operator, I want to authenticate with the extension, so that imports are associated with my account
    acceptance_criteria:
      - id: 5.1
        description: 未認証の場合、拡張機能はログインを促す
      - id: 5.2
        description: システムはSupabase Auth JWTを使用する
      - id: 5.3
        description: システムは認証状態を保持する

roles:
  - name: operator
    description: 不動産会社（オペレーター）
  - name: admin
    description: システム管理者
