feature: voice-io
title: 音声入出力要件定義

introduction: |
  キオスク端末における音声入力（Speech-to-Text）と音声出力（Text-to-Speech）機能。
  高齢者でも使いやすい音声インターフェースを提供し、自然な会話体験を実現する。

use_cases:
  - 不動産店舗のキオスク端末での利用
  - 高齢者や文字入力が苦手な顧客向け
  - ハンズフリーでの物件検索・内見予約

requirements:
  - id: 1
    title: 音声入力（Speech-to-Text）
    objective: As a kiosk user, I want to speak to the AI, so that I can search properties without typing
    acceptance_criteria:
      - id: 1.1
        description: マイクボタンをクリックすると、システムは音声録音を開始する
      - id: 1.2
        description: 録音中、システムはリアルタイムで音声波形を表示する
      - id: 1.3
        description: 録音停止後、システムはOpenAI Whisper APIで音声をテキスト変換する
      - id: 1.4
        description: 変換完了後、システムはテキストをAIに送信する
      - id: 1.5
        description: システムはWebM/MP3形式の音声をサポートする
      - id: 1.6
        description: システムは録音時間制限（最大60秒）を設ける

  - id: 2
    title: 音声出力（Text-to-Speech）
    objective: As a kiosk user, I want to hear the AI's response, so that I can have a natural conversation
    acceptance_criteria:
      - id: 2.1
        description: AIが応答完了すると、システムはGoogle Cloud TTS APIで音声を生成する
      - id: 2.2
        description: 音声生成完了後、システムは自動再生する
      - id: 2.3
        description: システムは日本語の自然な音声を生成する
      - id: 2.4
        description: 同じテキストを再度読み上げる場合、システムはキャッシュから音声を取得する
      - id: 2.5
        description: システムは読み上げ中にアバターの感情を切り替える（静止画方式）

  - id: 3
    title: 音声キャッシング
    objective: As a system, I want to cache audio files, so that I can reduce API costs and latency
    acceptance_criteria:
      - id: 3.1
        description: システムはテキストのハッシュ値をキーとしてSupabase Storageに音声を保存する
      - id: 3.2
        description: キャッシュが存在する場合、システムはAPIを呼び出さずにキャッシュから返す
      - id: 3.3
        description: システムは一定期間後にキャッシュを自動削除する（30日）
      - id: 3.4
        description: システムはよく使うフレーズ（挨拶等）を事前にキャッシュする

  - id: 4
    title: 音声コントロール
    objective: As a kiosk user, I want to control audio playback, so that I can pause or skip audio
    acceptance_criteria:
      - id: 4.1
        description: システムは再生/一時停止ボタンを提供する
      - id: 4.2
        description: システムは音量調整機能を提供する（キオスク設置時に設定）
      - id: 4.3
        description: 新しい応答が来た場合、前の音声は停止する
      - id: 4.4
        description: ユーザーが話し始めた場合、再生中の音声は停止する

roles:
  - name: kiosk_user
    description: キオスク端末を利用する店舗来店客（認証不要）
